@startuml
participant Core
participant Module
participant Vendor

Module -x Core : SubscribeRequest

...

Core -> Core : Startup

...

group async
Module -> Core : SubscribeRequest
else
Core --> Module : SubscribeResponse {status}
end

...

loop
	Vendor -> Module ++ : upstream event
	Module -> Core -- : Event
else async
    Core -> Module : Event
    Module -> Vendor : action
end
@enduml
